name: HTML Validator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v0.4.1
